apiVersion: v1
kind: Service
metadata:
  name: jenkins-cluster-ip-service
spec:
  # type: ClusterIP
  type: NodePort
  selector:
    component: jenkins
  ports:
    - port: 8080
      targetPort: 8080
